services:
  postgres:
    image: postgres
    container_name: postgres_investments
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: investments_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados
    restart: unless-stopped  # Recuperação automática
    networks:
      - invest_network

volumes:
  postgres_data:  # Volume para dados do PostgreSQL

networks:
  invest_network:  # Rede isolada para os serviços

